version: '3'
services:
  mongo1:
    build:
      context: ./mongo
    container_name: mongo1
    image: "mongo-replica-set:base"
    ports:
      - "27017:27017" # host:container
    volumes:
      - ~/mongo/mongo1:/data/db
    networks:
      - mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: qwe123
    command: "--bind_ip_all --replSet rep --keyFile /data/keyfile"
  mongo2:
    build:
      context: ./mongo
    container_name: mongo2
    image: "mongo-replica-set:base"
    ports:
      - "27018:27017"
    volumes:
      - ~/mongo/mongo2:/data/db
    networks:
      - mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: qwe123
    command: "--bind_ip_all --replSet rep --keyFile /data/keyfile"
    depends_on:
      - mongo1
  mongo3:
    build:
      context: ./mongo
    container_name: mongo3
    image: "mongo-replica-set:base"
    ports:
      - "27019:27017"
    volumes:
      - ~/mongo/mongo3:/data/db
    networks:
      - mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: qwe123
    command: "--bind_ip_all --replSet rep --keyFile /data/keyfile"
    depends_on:
      - mongo2

networks:
  mongo:
    driver: bridge
